### PR TITLE
[optionsframe] Center on parent frame

### PR DESCRIPTION
**Pull request by dstftw**

### CODE REVIEW

**Comment by MrS0m30n3** [comment]
Hi @dstftw 

I believe that calling CenterOnParent() every time someone clicks the "options" button is not the best idea, maybe some users want to keep the frames position.

You should move the CenterOnParent() at the \__init\__ of the MainFrame class.
This way, the options frame will be centered only the first time and not every time someone clicks the "options" button.

You basically need to remove the **frame.Centre()** from **\__init\__.py** line 78 and add the following 2 lines at MainFrame.\__init\__ 

```python
# Create options frame
self._options_frame = OptionsFrame(self)
 
+ self.Centre()
+ self._options_frame.CenterOnParent()
```

**Comment by dstftw** [comment]
Hi,
>maybe some users want to keep the frames position

Yes, but it not saved between sessions at the moment anyway (according to [this](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/youtube_dl_gui/optionsmanager.py#L302), only w/h is currently stored). Anyways, at least for the first time you run the program, dialogs should be centered on parent and not appear in opposite part of the screen.
Ok, I've restricted centering on parent only for the first run and implemented options window position storing.
I am not famiiar with wxPython, so feel free to change anything to fit wxPython-idiomatic style.
Thanks.

**Comment by dstftw** [comment]
>I was speaking about the current session.

I was aware of that.

>I don't really want to keep the windows positions between sessions.

What's the point in storing window size but not storing the position?

**Comment by MrS0m30n3** [comment]
> What's the point in storing window size but not storing the position?

The point is that if you want to implement the position storing for the options window you should also implement it for the main window and i don't really like storing the position and the size of the window at the settings.json. For the windows size i made an exception because i thought that storing the window size was useful.

I personally prefer keeping the windows centred and avoid having that extra code.

Anyway, if you still want to implement this you should
* Store the position for both main and options window
* By default both main and options window should be centred

**Comment by dstftw** [comment]
Fixed.

**Comment by MrS0m30n3** [comment]
Now it seems fine, thank you

**Pull request merged**
